#!/bin/sh
sxhkd &
compton &
mpd /home/lunarised/.mpd/mpd.conf &
feh --bg-fill ~/.bg &
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width	3
bspc config window_gap		12

bspc config split_ratio		0.5
bspc config borderless_monocle	true
bspc config 
polybar -r bar1
nm-applet 
